name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on main branch pushes

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Full history for proper versioning

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'  # Matches your Angular version
          cache: 'npm'  # Cache node_modules

      - name: Install dependencies
        run: npm ci  # Clean install

      - name: Build production version
        run: npm run build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'  # Memory allocation

      - name: Create necessary files
        run: |
          touch dist/github-portfolio/browser/.nojekyll
          cp src/404.html dist/github-portfolio/browser/404.html

      - name: List files
        run: ls -la dist/github-portfolio/browser

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/github-portfolio/browser
          clean: true
          single-commit: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}